# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(db_index=True)),
                ('label', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
            ],
        ),
    ]
