# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(db_index=True, max_length=150)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(0, 'unknown'), (1, 'boy'), (2, 'girl')], max_length=2)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('province', models.CharField(db_index=True, max_length=150)),
                ('country', models.CharField(db_index=True, max_length=150)),
            ],
        ),
    ]
